# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "2.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/golangci/golangci-lint/releases/download/v2.3.1/golangci-lint-2.3.1-darwin-amd64.tar.gz"
      sha256 "2f4412ffa77cb58ab3a7d065e1fff01ab714bb2b6fa06ad16ed793b6fc8d534d"

      def install
        bin.install "golangci-lint"
        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/golangci/golangci-lint/releases/download/v2.3.1/golangci-lint-2.3.1-darwin-arm64.tar.gz"
      sha256 "ca2b5bef12070add95ecc926c12c6301ca31619bcedde48bf63a89f3f0d2ec37"

      def install
        bin.install "golangci-lint"
        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/golangci/golangci-lint/releases/download/v2.3.1/golangci-lint-2.3.1-linux-amd64.tar.gz"
      sha256 "57c3a4c56b8363f7f1f695ac957b0bb474aca00c490bc5e949669a6c2ba5c432"
      def install
        bin.install "golangci-lint"
        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/golangci/golangci-lint/releases/download/v2.3.1/golangci-lint-2.3.1-linux-armv6.tar.gz"
      sha256 "bbdb9e335aa7501fe18997b9f659b3052938b7e6ef59a9f95eaf155595263c62"
      def install
        bin.install "golangci-lint"
        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/golangci/golangci-lint/releases/download/v2.3.1/golangci-lint-2.3.1-linux-arm64.tar.gz"
      sha256 "41f391f6cdefb48ffc2ff61c27ee10fd2085e9945a8e49cf1556210f8ae27888"
      def install
        bin.install "golangci-lint"
        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output
        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
